# Generated by Django 5.2.5 on 2025-08-18 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Região',
                'verbose_name_plural': 'Regiões',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distritos', to='arko.municipality')),
            ],
            options={
                'verbose_name': 'Distritos',
                'verbose_name_plural': 'Distritos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estados', to='arko.region')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='municipality',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='municipios', to='arko.state'),
        ),
    ]
