# Generated by Django 5.2.5 on 2025-08-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cnpg', models.CharField(help_text='CNPJ básico, 8 digitos', max_length=8, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(db_index=True, help_text='Razão Social ou Nome Empresarial', max_length=255)),
                ('natureza_juridica', models.CharField(help_text='Códgo da Natureza Jurídica', max_length=4)),
                ('qualificacao_responsavel', models.CharField(help_text='Capital Social da Empresa', max_length=2)),
                ('capital_social', models.DecimalField(decimal_places=2, help_text='Porte da Empresa (01, 03, 05)', max_digits=16)),
                ('ente_federativo_responsavel', models.CharField(blank=True, help_text='Ente Federativo Responsável', max_length=255)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
    ]
