# Generated by Django 5.2.5 on 2025-08-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0002_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='cnpg',
            new_name='cnpj',
        ),
    ]
