# Generated by Django 5.2.5 on 2025-08-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0003_rename_cnpg_company_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='porte_empresa',
            field=models.CharField(blank=True, help_text='Porte da Empresa (01, 03, 05)', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ente_federativo_responsavel',
            field=models.CharField(blank=True, help_text='Ente Federativo Responsável', max_length=255, null=True),
        ),
    ]
